### ISSUE TITLE
bitcoin for virtmart unable to load in version 3 joomla

### ISSUE THREAD

**Issue by RScottLewis** [AdvancedStyle/bitcointhai_virtuemart#1]
Need help loading your bitcoin extension (See error below).

It says to install it via the Joomla installer.
We don't have have virtuemart 2 installed. Does it work on version 3?
Is that's required.

And our Joomla is currently on version 3.62

Am I getting that error because it is for an older version of Joomla?

Can I/you make a wrapper for your extension so it loads? Please see https://docs.joomla.org/J3.x:Creating_a_Plugin_for_Joomla

With gratitude for the extension,

SCOTT LEWIS

**Comment by AdvancedStyle** [comment]
Sorry this plugin will only work with Joomla 2.5 + Virtuemart 2.

It would need a separate plugin for Joomla 3 + Virtuemart 3 as a lot of code changed.  We don't currently have enough demand of this to create a new plugin yet, but we may do in the future.
